### ISSUE TITLE
NRRD Patch failure

### ISSUE THREAD

**Issue by singamnv** [SlicerHeart/SlicerHeart#5]
Hi, 

I am attempting to patch a 3D Cartesian DICOM format of a mitral valve obtained from QLab 10 from a Philips machine. I initially tried using the Heart Slicer with Slicer 4 v 4.10.2. With this version, I cannot patch the DICOM due to an error regarding the software unable to recognize pydicom as a module. The error is "pydicom modue not found." Of note, I have both 2.7 and 3.7 releases of python and I have pydicom module with python when I attempt to access it outside of the Slicer4 software. 

I then updated Slicer to v4.11.0 and tried again. Now I can patch the DICOM but I am unable to write to NRRD Format. I've tried both versions of Slicer4 on both a Mac OSX Catalina and Windows 10 Pro x64. I have python installed on both devices. 

The error from the NRRD format bug is below: This error was copied from my Mac OSx Catalina x64 with Slicer4 v4.11.0. 

----------------------------------------------------
DICOM patching started...
Examining ./.DS_Store...
  Not DICOM file. Skipped.
Examining ./T001361759_17Jan2020_1HUAY5RH_.dcm...
  Patching...
  Writing DICOM...
  Created DICOM file: /Users/singamnv/Documents/3DDICOM/E2Results/T001361759_17Jan2020_1HUAY5RH_.dcm
sopClassUID 1.2.840.113543.6.6.1.3.10002 != supportedSOPClassUID 1.2.840.10008.5.1.4.1.1.3.1
  Writing NRRD...
Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/Extensions-28734/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/Philips4dUsDicomPatcher.py", line 103, in onPatchButton
    self.logic.patchDicomDir(self.inputDirSelector.currentPath, self.outputDirSelector.currentPath, self.enableDicomOutputCheckBox.checked, self.anonymizeDicomCheckBox.checked, self.enableNrrdOutputCheckBox.checked)
  File "/Applications/Slicer.app/Contents/Extensions-28734/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/Philips4dUsDicomPatcher.py", line 299, in patchDicomDir
    if self.convertUltrasoundDicomToNrrd(patchedFilePath, nrrdFilePath):
  File "/Applications/Slicer.app/Contents/Extensions-28734/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/Philips4dUsDicomPatcher.py", line 158, in convertUltrasoundDicomToNrrd
    sequenceNode = dicomPlugin.load(loadable)
  File "/Applications/Slicer.app/Contents/Extensions-28734/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/DicomUltrasoundPlugin.py", line 337, in load
    loadedNode = self.loadPhilips4DUSAsSequence(loadable)
  File "/Applications/Slicer.app/Contents/Extensions-28734/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/DicomUltrasoundPlugin.py", line 423, in loadPhilips4DUSAsSequence
    pixelSize = reduce(lambda x,y : x*y, pixelShape)
NameError: name 'reduce' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/Extensions-28734/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/Philips4dUsDicomPatcher.py", line 105, in onPatchButton
    self.addLog("Unexpected error: {0}".format(e.message))
AttributeError: 'NameError' object has no attribute 'message'

--------------
Thoughts?

Thanks,
Sarma

**Comment by lassoan** [comment]
Thanks for reporting this. I'll fix this today.

**Comment by lassoan** [comment]
The problem should be fixed in stable/preview releases that you download tomorrow or later. Please test it and let us know if it works.

**Comment by singamnv** [comment]
I tried again on the preview release I reinstalled Slicer4 just now on my MacBook. No luck. I have the same error. I installed Slicer 4.11.0 build 2020-1-20.  I have the same error when trying to write NRRD. 

 Writing DICOM...
  Created DICOM file: /Users/singamnv/Documents/3DDICOM/E2Results/T001361759_17Jan2020_1HUAY5RH_.dcm
sopClassUID 1.2.840.113543.6.6.1.3.10002 != supportedSOPClassUID 1.2.840.10008.5.1.4.1.1.3.1
  Writing NRRD...
Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/Extensions-28736/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/Philips4dUsDicomPatcher.py", line 103, in onPatchButton
    self.logic.patchDicomDir(self.inputDirSelector.currentPath, self.outputDirSelector.currentPath, self.enableDicomOutputCheckBox.checked, self.anonymizeDicomCheckBox.checked, self.enableNrrdOutputCheckBox.checked)
  File "/Applications/Slicer.app/Contents/Extensions-28736/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/Philips4dUsDicomPatcher.py", line 299, in patchDicomDir
    if self.convertUltrasoundDicomToNrrd(patchedFilePath, nrrdFilePath):
  File "/Applications/Slicer.app/Contents/Extensions-28736/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/Philips4dUsDicomPatcher.py", line 158, in convertUltrasoundDicomToNrrd
    sequenceNode = dicomPlugin.load(loadable)
  File "/Applications/Slicer.app/Contents/Extensions-28736/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/DicomUltrasoundPlugin.py", line 337, in load
    loadedNode = self.loadPhilips4DUSAsSequence(loadable)
  File "/Applications/Slicer.app/Contents/Extensions-28736/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/DicomUltrasoundPlugin.py", line 423, in loadPhilips4DUSAsSequence
    pixelSize = reduce(lambda x,y : x*y, pixelShape)
NameError: name 'reduce' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/Extensions-28736/SlicerHeart/lib/Slicer-4.11/qt-scripted-modules/Philips4dUsDicomPatcher.py", line 105, in onPatchButton
    self.addLog("Unexpected error: {0}".format(e.message))
AttributeError: 'NameError' object has no attribute 'message'

**Comment by singamnv** [comment]
Nevermind the message above! It seemed to work. Will keep you posted. Thanks, Sarma

**Comment by singamnv** [comment]
It worked perfectly! Thank you for your timely fix. It's much appreciated. Sincerely, Sarma

**Comment by lassoan** [comment]
Thanks for testing, I'm closing this issue then.
